// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Base desechable que Prisma usa para comprobar que una migración nueva
    // aplica limpia sobre el historial completo. Solo hace falta en desarrollo
    // (`migrate dev`): `prisma dev` levanta una para esto, y sin declararla
    // Prisma intenta reutilizar la principal y falla.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
